spring:
  application:
    name: api-gateway

server:
  port: 1101

zuul:
  routes:
    api-a:
      path: /eureka-client/**
      serviceId: eureka-client
eureka-client:
  ribbon:
      listOfServers: http://localhost:2101/, http://localhost:2102/
eureka:
  client:
    service-url: {"defaultZone":"http://localhost:11000/eureka/"}