spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:2006 #配置中心地址
server:
  port: 2007

#spring.application.name：对应配置文件规则中的{application}部分
#spring.cloud.config.profile：对应配置文件规则中的{profile}部分
#spring.cloud.config.label：对应配置文件规则中的{label}部分
#spring.cloud.config.uri：配置中心config-server的地址
