server:
  port: 11000

# 日志配置
logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: sc

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: {"defaultZone":"http://10.186.30.223:${server.port}/eureka/"}